server:
  port: 8090
nacos:
  config:
    server-addr: 127.0.0.1:8851,127.0.0.1:8852,127.0.0.1:8853

spring:
  servlet:
    multipart:
      max-request-size: 333
      max-file-size: 22
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
